---
grails:
    profile: web
    codegen:
        defaultPackage: se.su.it.ladok3
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
    plugin:
        databasemigration:
            changelogLocation: grails-app/migrations
            changelogFileName: changelog.groovy
            updateOnStart: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            jndiName: "java:comp/env/jdbc/ladok"
    test:
        dataSource:
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            dbcreate: create
    production:
        dataSource:
            jndiName: "java:comp/env/jdbc/ladok"
ladok3Settings:
    doch:
        certPath: ''
        certPassWord: ''
    gih:
        certPath: ''
        certPassWord: ''
    hh:
        certPath: ''
        certPassWord: ''
    hkr:
        certPath: ''
        certPassWord: ''
    kf:
        certPath: ''
        certPassWord: ''
    kmh:
        certPath: ''
        certPassWord: ''
    kth:
        certPath: ''
        certPassWord: ''
    lu:
        certPath: ''
        certPassWord: ''
    mau:
        certPath: ''
        certPassWord: ''
    sh:
        certPath: ''
        certPassWord: ''
    su:
        certPath: ''
        certPassWord: ''
